/**
 * Code Adapter
 * Generates Godot scripts (GDScript) and scene files
 */

import OpenAI from "openai";

class CodeAdapter {
  constructor() {
    this.openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY
    });
  }

  /**
   * Execute code generation
   */
  async execute({ gamePlan, assets }) {
    console.log(`[CodeAdapter] Generating code for: ${gamePlan.title}`);

    const scripts = [];
    const scenes = [];

    // Generate main game script
    const mainScript = await this.generateMainScript(gamePlan);
    scripts.push(mainScript);

    // Generate player script
    const playerEntity = gamePlan.entities.find(e => e.type === "player");
    if (playerEntity) {
      const playerScript = await this.generatePlayerScript(playerEntity, gamePlan);
      scripts.push(playerScript);
    }

    // Generate enemy scripts
    const enemies = gamePlan.entities.filter(e => e.type === "enemy");
    for (const enemy of enemies) {
      const enemyScript = await this.generateEnemyScript(enemy, gamePlan);
      scripts.push(enemyScript);
    }

    // Generate collectible script
    const collectibles = gamePlan.entities.filter(e => e.type === "collectible");
    if (collectibles.length > 0) {
      const collectibleScript = await this.generateCollectibleScript(collectibles[0]);
      scripts.push(collectibleScript);
    }

    // Generate UI script
    const uiScript = await this.generateUIScript(gamePlan.ui);
    scripts.push(uiScript);

    // Generate scene files
    const mainScene = this.generateMainScene(gamePlan, assets);
    scenes.push(mainScene);

    const playerScene = this.generatePlayerScene(playerEntity, assets);
    scenes.push(playerScene);

    const enemyScene = this.generateEnemyScene(enemies[0], assets);
    scenes.push(enemyScene);

    console.log(`[CodeAdapter] Generated ${scripts.length} scripts and ${scenes.length} scenes`);

    return { scripts, scenes };
  }

  /**
   * Generate main game manager script
   */
  async generateMainScript(gamePlan) {
    const code = `extends Node2D

# ${gamePlan.title} - Main Game Script
# Auto-generated by Game Forge

signal game_over(won)
signal score_changed(new_score)

var score: int = 0
var enemies_remaining: int = 0
var game_active: bool = true

@onready var player = $Player
@onready var ui = $UI

func _ready():
    enemies_remaining = get_tree().get_nodes_in_group("enemies").size()
    connect_signals()
    print("Game Started: ${gamePlan.title}")

func connect_signals():
    for enemy in get_tree().get_nodes_in_group("enemies"):
        enemy.connect("died", _on_enemy_died)
    
    if player:
        player.connect("died", _on_player_died)
        player.connect("collected", _on_item_collected)

func _on_enemy_died():
    enemies_remaining -= 1
    add_score(100)
    check_win_condition()

func _on_player_died():
    game_active = false
    emit_signal("game_over", false)
    # ${gamePlan.loseCondition}

func _on_item_collected(value: int):
    add_score(value)

func add_score(amount: int):
    score += amount
    emit_signal("score_changed", score)

func check_win_condition():
    # Win condition: ${gamePlan.winCondition}
    if enemies_remaining <= 0:
        game_active = false
        emit_signal("game_over", true)

func restart_game():
    get_tree().reload_current_scene()
`;

    return {
      name: "game_manager.gd",
      path: "scripts/game_manager.gd",
      content: code
    };
  }

  /**
   * Generate player script
   */
  async generatePlayerScript(playerEntity, gamePlan) {
    const speed = playerEntity.properties?.speed || 200;
    const health = playerEntity.properties?.health || 100;
    const hasShooting = playerEntity.behaviors?.includes("shooting");

    const code = `extends CharacterBody2D

# Player Script - Auto-generated by Game Forge

signal died
signal collected(value)
signal health_changed(new_health)

@export var speed: float = ${speed}
@export var max_health: int = ${health}

var health: int = max_health
var can_shoot: bool = true
var shoot_cooldown: float = 0.3

${hasShooting ? `
@onready var bullet_scene = preload("res://scenes/bullet.tscn")
@onready var muzzle = $Muzzle
` : ""}

func _ready():
    add_to_group("player")
    health = max_health

func _physics_process(delta):
    handle_movement()
    ${hasShooting ? "handle_shooting(delta)" : ""}
    move_and_slide()

func handle_movement():
    var input_dir = Vector2.ZERO
    input_dir.x = Input.get_axis("ui_left", "ui_right")
    input_dir.y = Input.get_axis("ui_up", "ui_down")
    
    velocity = input_dir.normalized() * speed
    
    # Rotate towards movement direction
    if velocity.length() > 0:
        rotation = velocity.angle()

${hasShooting ? `
func handle_shooting(delta):
    if Input.is_action_just_pressed("ui_accept") and can_shoot:
        shoot()

func shoot():
    can_shoot = false
    var bullet = bullet_scene.instantiate()
    bullet.global_position = muzzle.global_position
    bullet.rotation = rotation
    bullet.direction = Vector2.RIGHT.rotated(rotation)
    get_parent().add_child(bullet)
    
    await get_tree().create_timer(shoot_cooldown).timeout
    can_shoot = true
` : ""}

func take_damage(amount: int):
    health -= amount
    emit_signal("health_changed", health)
    
    if health <= 0:
        die()

func die():
    emit_signal("died")
    queue_free()

func collect(item):
    var value = item.value if item.has("value") else 10
    emit_signal("collected", value)
`;

    return {
      name: "player.gd",
      path: "scripts/player.gd",
      content: code
    };
  }

  /**
   * Generate enemy script
   */
  async generateEnemyScript(enemyEntity, gamePlan) {
    const speed = enemyEntity.properties?.speed || 100;
    const health = enemyEntity.properties?.health || 30;
    const damage = enemyEntity.properties?.damage || 10;
    const hasChase = enemyEntity.behaviors?.includes("chase");
    const hasPatrol = enemyEntity.behaviors?.includes("patrol");

    const code = `extends CharacterBody2D

# Enemy Script - Auto-generated by Game Forge

signal died

@export var speed: float = ${speed}
@export var max_health: int = ${health}
@export var damage: int = ${damage}
@export var detection_range: float = 200.0

var health: int = max_health
var player: Node2D = null
var patrol_points: Array = []
var current_patrol_index: int = 0

${hasPatrol ? `
var patrol_wait_time: float = 1.0
var waiting: bool = false
` : ""}

func _ready():
    add_to_group("enemies")
    health = max_health
    find_player()
    ${hasPatrol ? "setup_patrol()" : ""}

func find_player():
    var players = get_tree().get_nodes_in_group("player")
    if players.size() > 0:
        player = players[0]

${hasPatrol ? `
func setup_patrol():
    # Create patrol points around spawn position
    var origin = global_position
    patrol_points = [
        origin + Vector2(100, 0),
        origin + Vector2(100, 100),
        origin + Vector2(0, 100),
        origin
    ]
` : ""}

func _physics_process(delta):
    if player == null:
        find_player()
        return
    
    var distance_to_player = global_position.distance_to(player.global_position)
    
    ${hasChase ? `
    if distance_to_player < detection_range:
        chase_player()
    else:
        ${hasPatrol ? "patrol()" : "velocity = Vector2.ZERO"}
    ` : hasPatrol ? "patrol()" : ""}
    
    move_and_slide()

${hasChase ? `
func chase_player():
    var direction = (player.global_position - global_position).normalized()
    velocity = direction * speed
    rotation = velocity.angle()
` : ""}

${hasPatrol ? `
func patrol():
    if waiting:
        return
    
    if patrol_points.size() == 0:
        return
    
    var target = patrol_points[current_patrol_index]
    var direction = (target - global_position).normalized()
    velocity = direction * speed * 0.5
    
    if global_position.distance_to(target) < 10:
        waiting = true
        velocity = Vector2.ZERO
        await get_tree().create_timer(patrol_wait_time).timeout
        current_patrol_index = (current_patrol_index + 1) % patrol_points.size()
        waiting = false
` : ""}

func take_damage(amount: int):
    health -= amount
    # Flash red effect
    modulate = Color.RED
    await get_tree().create_timer(0.1).timeout
    modulate = Color.WHITE
    
    if health <= 0:
        die()

func die():
    emit_signal("died")
    queue_free()

func _on_body_entered(body):
    if body.is_in_group("player"):
        body.take_damage(damage)
`;

    return {
      name: "enemy.gd",
      path: "scripts/enemy.gd",
      content: code
    };
  }

  /**
   * Generate collectible script
   */
  async generateCollectibleScript(collectible) {
    const value = collectible.properties?.value || 10;

    const code = `extends Area2D

# Collectible Script - Auto-generated by Game Forge

@export var value: int = ${value}
@export var bob_speed: float = 2.0
@export var bob_height: float = 5.0

var start_y: float

func _ready():
    add_to_group("collectibles")
    start_y = position.y
    connect("body_entered", _on_body_entered)

func _process(delta):
    # Bobbing animation
    position.y = start_y + sin(Time.get_ticks_msec() * 0.001 * bob_speed) * bob_height

func _on_body_entered(body):
    if body.is_in_group("player"):
        if body.has_method("collect"):
            body.collect(self)
        queue_free()
`;

    return {
      name: "collectible.gd",
      path: "scripts/collectible.gd",
      content: code
    };
  }

  /**
   * Generate UI script
   */
  async generateUIScript(uiConfig) {
    const code = `extends CanvasLayer

# UI Script - Auto-generated by Game Forge

@onready var health_bar = $HealthBar
@onready var score_label = $ScoreLabel
@onready var game_over_panel = $GameOverPanel
@onready var win_label = $GameOverPanel/WinLabel
@onready var lose_label = $GameOverPanel/LoseLabel

func _ready():
    game_over_panel.visible = false
    
    # Connect to game manager
    var game_manager = get_parent()
    if game_manager:
        game_manager.connect("score_changed", _on_score_changed)
        game_manager.connect("game_over", _on_game_over)
    
    # Connect to player
    var players = get_tree().get_nodes_in_group("player")
    if players.size() > 0:
        players[0].connect("health_changed", _on_health_changed)

func _on_health_changed(new_health):
    ${uiConfig.showHealth ? 'health_bar.value = new_health' : 'pass'}

func _on_score_changed(new_score):
    ${uiConfig.showScore ? 'score_label.text = "Score: " + str(new_score)' : 'pass'}

func _on_game_over(won: bool):
    game_over_panel.visible = true
    win_label.visible = won
    lose_label.visible = not won

func _on_restart_pressed():
    get_tree().reload_current_scene()
`;

    return {
      name: "ui.gd",
      path: "scripts/ui.gd",
      content: code
    };
  }

  /**
   * Generate main scene file
   */
  generateMainScene(gamePlan, assets) {
    const sceneTscn = `[gd_scene load_steps=5 format=3]

[ext_resource type="Script" path="res://scripts/game_manager.gd" id="1"]
[ext_resource type="PackedScene" path="res://scenes/player.tscn" id="2"]
[ext_resource type="PackedScene" path="res://scenes/enemy.tscn" id="3"]
[ext_resource type="PackedScene" path="res://scenes/ui.tscn" id="4"]

[node name="Main" type="Node2D"]
script = ExtResource("1")

[node name="Background" type="Sprite2D" parent="."]
texture = ExtResource("background")

[node name="Player" parent="." instance=ExtResource("2")]
position = Vector2(512, 300)

[node name="Enemies" type="Node2D" parent="."]

[node name="Enemy1" parent="Enemies" instance=ExtResource("3")]
position = Vector2(800, 200)

[node name="Enemy2" parent="Enemies" instance=ExtResource("3")]
position = Vector2(200, 400)

[node name="Enemy3" parent="Enemies" instance=ExtResource("3")]
position = Vector2(700, 500)

[node name="Collectibles" type="Node2D" parent="."]

[node name="UI" parent="." instance=ExtResource("4")]
`;

    return {
      name: "main.tscn",
      path: "scenes/main.tscn",
      content: sceneTscn
    };
  }

  /**
   * Generate player scene file
   */
  generatePlayerScene(playerEntity, assets) {
    const playerAsset = assets.find(a => a.entityType === "player");
    
    const sceneTscn = `[gd_scene load_steps=3 format=3]

[ext_resource type="Script" path="res://scripts/player.gd" id="1"]
[ext_resource type="Texture2D" path="res://assets/sprites/player.png" id="2"]

[node name="Player" type="CharacterBody2D"]
script = ExtResource("1")

[node name="Sprite2D" type="Sprite2D" parent="."]
texture = ExtResource("2")

[node name="CollisionShape2D" type="CollisionShape2D" parent="."]
shape = SubResource("RectangleShape2D_player")

[node name="Muzzle" type="Marker2D" parent="."]
position = Vector2(20, 0)

[sub_resource type="RectangleShape2D" id="RectangleShape2D_player"]
size = Vector2(32, 32)
`;

    return {
      name: "player.tscn",
      path: "scenes/player.tscn",
      content: sceneTscn
    };
  }

  /**
   * Generate enemy scene file
   */
  generateEnemyScene(enemyEntity, assets) {
    const sceneTscn = `[gd_scene load_steps=3 format=3]

[ext_resource type="Script" path="res://scripts/enemy.gd" id="1"]
[ext_resource type="Texture2D" path="res://assets/sprites/enemy.png" id="2"]

[node name="Enemy" type="CharacterBody2D"]
script = ExtResource("1")

[node name="Sprite2D" type="Sprite2D" parent="."]
texture = ExtResource("2")

[node name="CollisionShape2D" type="CollisionShape2D" parent="."]
shape = SubResource("CircleShape2D_enemy")

[node name="DetectionArea" type="Area2D" parent="."]

[node name="DetectionShape" type="CollisionShape2D" parent="DetectionArea"]
shape = SubResource("CircleShape2D_detection")

[sub_resource type="CircleShape2D" id="CircleShape2D_enemy"]
radius = 16.0

[sub_resource type="CircleShape2D" id="CircleShape2D_detection"]
radius = 200.0
`;

    return {
      name: "enemy.tscn",
      path: "scenes/enemy.tscn",
      content: sceneTscn
    };
  }
}

export default CodeAdapter;