sonar.projectKey=game-forge-main
sonar.projectName=Game Forge - Main
sonar.organization=game-forge-studio
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**
